spring.application.name=notificaiton_service
server.port=8089

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=vinaysemwal392@gmail.com
spring.mail.password=qeiuhaqjsrjmcvny
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
